#!/usr/bin/env python3

# rosrun hello_ros mtsub
# rosrun hello_ros mtpub

import rospy
from std_msgs.msg import String


class Msub:
    def __init__(self):
        self.sub = rospy.Subscriber('message', String, self.sub_callback)

    def sub_callback(self, msg: String):
        rospy.loginfo(f"들어온 메세지 by msub: {msg.data}")

def main():
    rospy.init_node('msub')
    node = Msub()
    while not rospy.is_shutdown():
        rospy.spin()

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass