#!/usr/bin/env python3

import rospy
from std_msgs.msg import Header


class MTsub:
    def __init__(self):
        self.pub = rospy.Subscriber('time', Header, self.sub_callback)


    def sub_callback(self, msg:Header):
        rospy.loginfo(f"input message:{msg.frame_id}")
        rospy.loginfo(f"input message:{msg.stamp.secs}")

    def print_hello(self, _event):
        self.data.frame_id = "base time by MTpub"
        self.data.stamp = rospy.Time.now()
        rospy.loginfo(self.data.frame_id)
        rospy.loginfo(f'{self.data.stamp.secs} : {self.data.stamp.nsecs}')
        self.pub.publish(self.data)


def main():
    rospy.init_node('hello')
    node = MTsub()
    while not rospy.is_shutdown():
        rospy.spin()

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass